### ISSUE TITLE
Issue with pip installation

### ISSUE THREAD

**Issue by janTOffermann** [scikit-hep/fastjet#46]
Hi there.

I recently tried to install fastjet using `pip`, but doing so seems to yield an empty package:
```
$ pip install fastjet
Collecting fastjet
  Using cached fastjet-0.0.1.1-py3-none-any.whl (1.2 kB)
Installing collected packages: fastjet
Successfully installed fastjet-0.0.1.1
```

Navigating to where `pip` has actually installed the package (`.../site-packages/fastjet/`), there is only a file `__init__.py` that contains one line:
```
pass
``` 
Likewise, the files in `.../site-packages/fastjet=0.0.1.1.dist-info/` are also more or less empty.

On a perhaps separate issue, the pypi package "button" in [the readme](https://github.com/scikit-hep/fastjet/blob/main/README.md) shows version `0.0.3`, but this links to [the pypi page for *pyjet*](https://pypi.org/project/fastjet/) (which is somewhat confusingly labeled as "fastjet" although it is installed as `pip install pyjet`).

Here's some information on my setup:
OS: Ubuntu 18.04.5 LTS
Python: 3.8 (via conda)
pip: 21.1.3 (via conda)

And here's the conda environment that I'm using: [[Google Drive Link]](https://drive.google.com/file/d/1dk78NhOouGUk3gy3TdCjGbweQRVYh8NG/view?usp=sharing)

**Comment by aryan26roy** [comment]
Hi @janTOffermann , thank you for commenting. 
Currently the pypi release that you can download is just a dummy release that was made by the previous owner of the pypi name fastjet. This new package is scheduled to be released under the same pypi name however we are still sorting out some issues with the CD. (This package is under early development and we will be releasing some pre-release versions soon.). 
The pypi page you are referring to is not the pypi page of pyjet (it's this one: https://pypi.org/project/pyjet/). The previous owner of the name fastjet on pypi was also the developer of pyjet (which is why it says pyjet on the fastjet pypi page).
