### ISSUE TITLE
Vulnerable shared libraries might make fastjet vulnerable. Can you help upgrade to patch versions?

### ISSUE THREAD

**Issue by andy201709** [scikit-hep/fastjet#80]
Hi, @aryan26roy , @jpivarski , I'd like to report a vulnerability issue in **fastjet_3.3.4.0rc9**.
### Dependency Graph between Python and Shared Libraries
![image](https://user-images.githubusercontent.com/101270230/161096376-0a14d875-8d0f-4fe6-9e04-4777fba89eb3.png)
### Issue Description
As shown in the above dependency graph, **fastjet_3.3.4.0rc9** directly or transitively depends on ***17*** C libraries (.so). However, I noticed that one C library is vulnerable, containing the following CVEs:
`libgmp-afec2dd4.so.10.2.0` from C project **gmp(version:6.1.0)** exposed ***1*** vulnerabilities:
[CVE-2021-43618](https://nvd.nist.gov/vuln/detail/CVE-2021-43618)
### Suggested Vulnerability Patch Versions
No official patch version released, but ***gmp*** has fixed the vulnerability in [patch](https://gmplib.org/repo/gmp-6.2/rev/561a9c25298e).

Python build tools cannot report vulnerable C libraries, which may induce potential security issues to many downstream Python projects.
As a popular python package (**fastjet** has **1,208** downloads per month), could you please upgrade the above shared libraries to their patch versions?

Thanks for your help~
Best regards,
Andy

**Comment by jpivarski** [comment]
Hi, thanks for the warning!

I can see that this is a test of a new security vulnerability tool that you've developed, since you've made [28 similar reports](https://github.com/andy201709) on various packages in the past 4 days.

Fortunately for us, @rt121212121 has investigated the libgmp issue and recognized that it is a 32-bit problem (in https://github.com/electrumsv/electrumsv-secp256k1/issues/5#issuecomment-1083514561). I say "fortunately for us" because I don't know how we would evaluate that or respond to it. libgmp is not built by FastJet: it's something we get from manylinux, but we only build 64-bit.

**Comment by rt121212121** [comment]
What the project electrumsv-secp256k1 is derived from did, and we do, is we download a pinned gmp release into the manylinux docker thing and build and install it. Then compile against that. What we would do beyond that had we needed to patch this, was to apply the patch after downloading/extracting the gmp source before building it.
