### ISSUE TITLE
JetDefinition fails with int

### ISSUE THREAD

**Issue by goi42** [scikit-hep/fastjet#92]
If I call `JetDefinition` with an integer, I get the unhelpful error message:
```text
fastjet::Error:  The jet algorithm you requested (2) should be constructed with 1 parameter(s) but was called with 0 parameter(s)
```
Calling with a float causes no such problem. Reproducer below

By the way, this error does not seem to have been properly implemented in python:
```text
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
Input In [7], in <cell line: 1>()
fastjet::Error:  The jet algorithm you requested (2) should be constructed with 1 parameter(s) but was called with 0 parameter(s)

----> 1 jet_def = fastjet.JetDefinition(fastjet.antikt_algorithm, 1)

File ~/miniconda/envs/LHCb-geometry/lib/python3.9/site-packages/fastjet/_swig.py:2793, in JetDefinition.__init__(self, *args)
   2783 def __init__(self, *args):
   2784     r"""
   2785 
   2786     `JetDefinition(JetAlgorithm jet_algorithm_in, double R_in, RecombinationScheme
   (...)
   2791 
   2792     """
-> 2793     _fastjet.JetDefinition_swiginit(self, _fastjet.new_JetDefinition(*args))

SystemError: _PyErr_SetObject: exception <class 'fastjet._swig.Error'> is not a BaseException subclass
```

___
Reproducer:
```python
import fastjet

jet_def = fastjet.JetDefinition(fastjet.antikt_algorithm, 1.)  # no problems
jet_def = fastjet.JetDefinition(fastjet.antikt_algorithm, 1)  # raises error
```

**Comment by jpivarski** [comment]
These are good error reports; thank you!

This particular one looks like it's passing on the error SWIG generated, and SWIG might be old enough not to know that arbitrary objects are no longer legal to use as exceptions. Since we wrap these functions, an easy thing that we could do is ensure that the second argument of `fastjet.JetDefinition` is always cast as `float`, which would also help in cases when it's `np.float32` or some other Python type that has a `__float__` method.

But just sanitizing the arguments wouldn't help if there are more ways SWIG can raise errors. I wonder if we can change the inheritance of the `fastjet._swig.Error` object, and add `Exception` to its `__bases__`? It's very likely an extension type. Maybe we're not getting the most recent version of SWIG bindings, and that can be updated?

The library is in need of these kinds of touch-ups; we need to identify a new maintainer now that @aryan26roy's development project is over. It could be a good student project, now that we're getting usage feedback like this. (The above is exactly the sort of thing that users run into, but a developer wouldn't necessarily think of testing. That's why we need to close this loop!)
